apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: my-first-app-task
  namespace: tekton-pipelines
  labels:
    app: my-first-app
spec:
  inputs:
    resources:
    - name: app
      type: git
    params:
    - name: pathToDockerFile
      description: The path to the dockerfile to build
      default: /workspace/app/Dockerfile
    - name: pathToContext
      description: The build context used by Kaniko
      default: /workspace/app
  steps:
  - name: build-and-push
    image: gcr.io/kaniko-project/executor:v0.13.0
    env:
    - name: DOCKER_CONFIG
      value: /tekton/home/.docker/
    workingDir: ""
    command:
    - /kaniko/executor
    args:
    - --dockerfile=$(inputs.params.pathToDockerFile)
    - --destination="registry.cn-shanghai.aliyuncs.com/zjops/my-first-app:0.0.1"
    - --context=$(inputs.params.pathToContext)
    - --skip-tls-verify